
# config/meta.yml
meta_product_name: "Time To Surf !"
meta_title: "Time to Surf - The easiest way to find the best surf spot according to your level and needs!"
meta_description: "Time to surf is for independant surfers with a range of levels. It is the easiest way to find the best surf spot according to your level and needs!"
meta_image: "facebook-card.jpg"
twitter_account: "@APatouillaud"   # required for Twitter Cards
